apiVersion: v2
description: A Helm chart for Peacock Service on Kubernetes
icon: https://raw.githubusercontent.com/spring-financial-group/peacock/main/images/peacock.png
name: peacock
version: 0.1.0-SNAPSHOT

dependencies:
  - name: mongodb
    version: 18.1.1
    repository: oci://registry-1.docker.io/bitnamicharts
    condition: mongodb.useInternalInstance
