apiVersion: v2
description: A Helm chart for Peacock Service on Kubernetes
icon: https://raw.githubusercontent.com/spring-financial-group/peacock/main/images/peacock.png
name: peacock
version: 1.15.0

dependencies:
  - condition: mongodb.useInternalInstance
    name: mongodb
    repository: oci://registry-1.docker.io/cloudpirates
    version: 0.7.1
